packages:
  - 'packages/*'
  - 'packages/dux/idb-dux'
  - 'sandbox/*'
  - 'www'
  - 'www/_emails/replace-images'

overrides:
  caniuse-lite: 1.0.30001790

allowBuilds:
  esbuild: true
  msw: true

minimumReleaseAge: 5760
minimumReleaseAgeExclude:
  - '@mszr/*'
