import type { AttrsDefs, AuthState, BackwardsCompatibleSchema, CardinalityKind, CheckMagicCodeParams, CheckMagicCodeResponse, Config, ConnectionStatus, CreateParams, CreateReadStreamOpts, CreateWriteStreamOpts, DataAttrDef, DeleteFileResponse, EntitiesDef, EntitiesWithLinks, EntityDef, ExchangeCodeForTokenParams, FileOpts, IInstantDatabase, InstantConfig, InstantObject, InstantReadableStream, InstantRules, InstantSchemaDef, InstantUnknownSchema, InstantUnknownSchemaDef, InstantWritableStream, InstaQLEntity, InstaQLEntitySubquery, InstaQLFields, InstaQLParams, InstaQLResult, LinkAttrDef, LinkDef, LinkParams, LinksDef, PresenceOf, PresencePeer, Query, QueryResponse, ResolveAttrs, RoomHandle, RoomsDef, RoomsOf, SendMagicCodeParams, SendMagicCodeResponse, SignInWithIdTokenParams, StoreInterfaceStoreName, SyncTableCallback, SyncTableCallbackEvent, SyncTableInitialSyncBatch, SyncTableInitialSyncComplete, SyncTableLoadFromStorage, SyncTableSetupError, SyncTableSyncTransaction, TopicOf, TopicsOf, TransactionChunk, UpdateParams, UploadFileResponse, User, ValidQuery, ValueTypes, VerifyMagicCodeParams, VerifyResponse } from '@instantdb/core'
import type { DefineDbOptions } from './defineDb.js'
import type {
  TypedQueryForSchema,
  ValidateTypedQueryForSchema,
} from './defineQuery.js'

import type {
  InstantVuxInitConfig,
  QueryOnceXResult,
  UseAuthResult,
  UseAuthXRefs,
  UseAuthXResult,
  UseAuthXState,
  UseInfiniteQueryResult,
  UseInfiniteQueryXRefs,
  UseInfiniteQueryXResult,
  UseInfiniteQueryXState,
  UseQueryOptions,
  UseQueryXRefs,
  UseQueryXResult,
  UseQueryXState,
  UseUserOptions,
  UseUserRequirement,
  UseUserValue,
} from './InstantVuxDatabase.js'
import type {
  UsePresenceXRefs,
  UsePresenceXResult,
  UsePresenceXState,
  UseTypingIndicatorXRefs,
  UseTypingIndicatorXResult,
  UseTypingIndicatorXState,
} from './InstantVuxRoom.js'

import {
  createInstantRouteHandler,
  i,
  id,
  InstantAPIError,
  lookup,
  setInstantWarningsEnabled,
  StoreInterface,
  SyncTableCallbackEventType,
  tx,
} from '@instantdb/core'
import Cursors from './Cursors.js'
import { defineDb } from './defineDb.js'
import { defineQuery } from './defineQuery.js'

import {
  init,
  InstantVuxDatabase,
} from './InstantVuxDatabase.js'

import { InstantVuxRoom, rooms } from './InstantVuxRoom.js'
import SignedIn from './SignedIn.js'
import SignedOut from './SignedOut.js'

export {
  type AttrsDefs,
  type AuthState,
  type BackwardsCompatibleSchema,
  type CardinalityKind,
  type CheckMagicCodeParams,
  type CheckMagicCodeResponse,
  type Config,
  type ConnectionStatus,
  createInstantRouteHandler,
  type CreateParams,
  type CreateReadStreamOpts,
  type CreateWriteStreamOpts,
  Cursors,
  type DataAttrDef,
  defineDb,
  type DefineDbOptions,
  defineQuery,
  type DeleteFileResponse,
  type EntitiesDef,
  type EntitiesWithLinks,
  type EntityDef,
  type ExchangeCodeForTokenParams,
  type FileOpts,
  i,
  id,
  type IInstantDatabase,
  init,
  InstantAPIError,
  type InstantConfig,
  type InstantObject,
  type InstantReadableStream,
  type InstantRules,
  type InstantSchemaDef,
  type InstantUnknownSchema,
  type InstantUnknownSchemaDef,
  InstantVuxDatabase,
  type InstantVuxInitConfig,
  InstantVuxRoom,
  type InstantWritableStream,
  type InstaQLEntity,
  type InstaQLEntitySubquery,
  type InstaQLFields,
  type InstaQLParams,
  type InstaQLResult,
  type LinkAttrDef,
  type LinkDef,
  type LinkParams,
  type LinksDef,
  lookup,
  type PresenceOf,
  type PresencePeer,
  type Query,
  type QueryOnceXResult,
  type QueryResponse,
  type ResolveAttrs,
  type RoomHandle,
  rooms,
  type RoomsDef,
  type RoomsOf,
  type SendMagicCodeParams,
  type SendMagicCodeResponse,
  setInstantWarningsEnabled,
  SignedIn,
  SignedOut,
  type SignInWithIdTokenParams,
  StoreInterface,
  type StoreInterfaceStoreName,
  type SyncTableCallback,
  type SyncTableCallbackEvent,
  SyncTableCallbackEventType,
  type SyncTableInitialSyncBatch,
  type SyncTableInitialSyncComplete,
  type SyncTableLoadFromStorage,
  type SyncTableSetupError,
  type SyncTableSyncTransaction,
  type TopicOf,
  type TopicsOf,
  type TransactionChunk,
  tx,
  type TypedQueryForSchema,
  type UpdateParams,
  type UploadFileResponse,
  type UseAuthResult,
  type UseAuthXRefs,
  type UseAuthXResult,
  type UseAuthXState,
  type UseInfiniteQueryResult,
  type UseInfiniteQueryXRefs,
  type UseInfiniteQueryXResult,
  type UseInfiniteQueryXState,
  type UsePresenceXRefs,
  type UsePresenceXResult,
  type UsePresenceXState,
  type UseQueryOptions,
  type UseQueryXRefs,
  type UseQueryXResult,
  type UseQueryXState,
  type User,
  type UseTypingIndicatorXRefs,
  type UseTypingIndicatorXResult,
  type UseTypingIndicatorXState,
  type UseUserOptions,
  type UseUserRequirement,
  type UseUserValue,
  type ValidateTypedQueryForSchema,
  type ValidQuery,
  type ValueTypes,
  type VerifyMagicCodeParams,
  type VerifyResponse,
}
